version: '3.2'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=canine_production,canine_development
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    depends_on:
      - postgres
      - redis
    stdin_open: true
    tty: true
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "3200:3200"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432
      - REDIS_URL=redis://redis:6379
      - PORT=${PORT:-3000}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - LOCAL_MODE=true
    volumes:
      - .:/rails
      - node_modules:/rails/node_modules
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres:
  node_modules:
