apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <%= @project.name %>
  name: <%= @project.name %>
data:
  <% @project.environment_variables.each do |environment_variable| %>
  <%= environment_variable.name %>: "<%= environment_variable.value.gsub('"', '\\"') %>"
  <% end %>
