apiVersion: batch/v1
kind: CronJob
metadata:
  name: <%= project.name %>
spec:
  schedule: <%= project.cron_schedule.schedule %>
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: <%= project.name %>
            image: <%= project.container_registry_url %>
            imagePullPolicy: Always
            command: <% project.command.split(' ').each do |c| %>
              - <%= c %>
            <% end %>
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: dockerconfigjson-github-com
