apiVersion: batch/v1
kind: CronJob
metadata:
  name: <%= service.name %>
  namespace: <%= project.name %>
  labels:
    caninemanaged: 'true'
    app: <%= service.name %>
spec:
  schedule: "<%= service.cron_schedule.schedule %>"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: <%= project.name %>
            image: <%= project.container_registry_url %>
            imagePullPolicy: Always
            command: <% service.command.split(' ').each do |c| %>
              - <%= c %>
            <% end %>
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: dockerconfigjson-github-com
