apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= service.name %>
  namespace: <%= project.name %>
  labels:
    app: <%= service.name %>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <%= service.name %>
  template:
    metadata:
      labels:
        app: <%= service.name %>
    spec:
      containers:
      - name: <%= project.name %>
        image: <%= project.container_registry_url %>
        imagePullPolicy: Always
        env:
        <% environment_variables.each do |env| %>
          - name: <%= env.name %>
            value: <%= env.value %>
        <% end %>
        ports:
        - containerPort: <%= service.container_port %>
      imagePullSecrets:
      - name: dockerconfigjson-github-com
