apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%= service.name %>-ingress
  namespace: <%= project.name %>
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    <% service.domains.each do |domain| %>
    - <%= domain.domain_name %>
    <% end %>
    secretName: example-tls
  rules:
  <% service.domains.each do |domain| %>
  - host: <%= domain.domain_name %>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <%= service.name %>-service
            port:
              number: 80
  <% end %>