apiVersion: v1
kind: Pod
metadata:
  name: <%= name %>
  namespace: <%= project.name %>
  labels:
    caninemanaged: 'true'
    oneoff: 'true'
spec:
  restartPolicy: Never
  containers:
  - name: <%= project.name %>
    image: <%= project.container_registry_url %>
    command:
      - sleep
      - "3600"
    envFrom:
    - configMapRef:
        name: <%= project.name %>
  imagePullSecrets:
  - name: dockerconfigjson-github-com
