apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <%= name %>
  namespace: <%= project.name %>
  labels:
    caninemanaged: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <%= volume.size %>
  storageClassName: manual
