apiVersion: v1
kind: Service
metadata:
  name: <%= service.name %>-service
  namespace: <%= project.name %>
  labels:
    app: <%= service.name %>
spec:
  selector:
    app: <%= service.name %>
  ports:
    - protocol: TCP
      port: 80
      targetPort: <%= service.container_port %>
  type: ClusterIP
