apiVersion: v1
kind: Config
clusters:
- name: example-cluster
  cluster:
    server: https://example-cluster.k8s.example.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM...
contexts:
- name: example-context
  context:
    cluster: example-cluster
    namespace: default
    user: example-user
current-context: example-context
preferences: {}
users:
- name: example-user
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM...
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQo...