helm:
  charts:
    - name: postgresql
      chart_url: bitnami/postgresql
      friendly_name: PostgreSQL
      logo: /images/helm/postgresql.png
      template:
        - name: Storage
          key: primary.persistence.size
          type: size
          default: 10Gi
          required: true
    - name: redis
      chart_url: bitnami/redis
      friendly_name: Redis
      logo: /images/helm/redis.png
      template:
        - name: Storage
          key: master.persistence.size
          type: size
          default: 2Gi
          required: true
        - name: Replicas
          key: replica.replicaCount
          type: integer
          default: 0
          hidden: true
    - name: metabase
      chart_url: pmint93/metabase
      friendly_name: Metabase
      logo: /images/helm/metabase.png
      template:
        - name: Connection URI
          key: database.connectionURI
          type: string
          required: true
        - name: Database Type
          key: database.type
          type: enum
          options:
            - postgres
            - mysql
          required: true
    - name: elasticsearch
      logo: /images/helm/elasticsearch.png
      chart_url: bitnami/elasticsearch
      friendly_name: Elasticsearch
      template:
        - name: resources.limits.storage
          key: resources.limits.storage
          type: size
          default: 10Gi
    - name: supabase
      logo: /images/helm/supabase.png
      repository: https://github.com/supabase-community/supabase-kubernetes
      coming_soon: true
      
    - name: sentry
      logo: /images/helm/sentry.png
      repository: https://sentry-kubernetes.github.io/charts
      coming_soon: true
      
    - name: clickhouse
      logo: /images/helm/clickhouse.png
      repository: https://clickhouse.github.io/clickhouse-helm
      coming_soon: true
      
    - name: superset
      logo: /images/helm/superset.png
      repository: https://apache.github.io/superset
      coming_soon: true
      
    - name: grafana
      logo: /images/helm/grafana.png
      repository: https://grafana.github.io/helm-charts
      coming_soon: true
      
    - name: helm_chart
      friendly_name: "Helm Chart"
      logo: /images/helm/helm_chart.png
      controller: "helm-search"
      metadata:
        - name: Name
          key: helm_chart.name
          type: string
          hidden: false
    #- name: prometheus
    #  logo: /images/helm/prometheus.png
    #  repository: https://prometheus-community.github.io/helm-charts
    #- name: wordpress
    #  repository: https://charts.bitnami.com/bitnami