name: System Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the stack
      run: docker-compose build

    - name: Start containers
      run: |
        docker-compose up -d
        sleep 10  # Give the containers time to fully start

    - name: Run system tests
      run: |
        docker-compose exec -T web bundle exec rspec spec/system/local
        
    - name: Display logs on failure
      if: failure()
      run: docker-compose logs

    - name: Clean up
      if: always()
      run: docker-compose down